# Generated by Django 3.1.7 on 2021-04-12 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OurProject', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='apartment_id',
        ),
        migrations.AddField(
            model_name='apartments',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='OurProject.user'),
        ),
    ]
